server:
  port: 8094
#  ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

spring:
  application:
    name: query-logs
######################### SECURITY #####################
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/realms/meysam
      client:
        registration:
          keycloak:
            client-id: spring-cloud-microservices
            #            authorization-grant-type: password
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:8080/realms/meysam
            user-name-attribute: preferred_username





