server:
  port: 8010

spring:
  application:
    name: discovery-service
#  security:
#    user:
#      name: test
#      password: test

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8010/eureka


#  instance:
#    lease-renewal-interval-in-seconds=10: