# a random port number will be assigned for each instance of app:
server:
  port: 8091
#  ${PORT:0}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      # the url by which the client apps communicate with Eureka server
      defaultZone: http://localhost:8010/eureka

spring:
  application:
    name: auth-ws
  messages:
    #i18n
    basename: messages/messages
  profiles:
    active: dev
oauth:
  client:
    secret: yw0cp520q2s9SfBQ809njnTI8CQwWc66

keycloak:
  get:
    token:
      url: http://127.0.0.1:8080/realms/meysam/protocol/openid-connect/token
  register:
    user:
      url: http://127.0.0.1:8080/admin/realms/meysam/users

web:
  client:
    time-out:
      connection: 10000
      response: 10000


