server:
  port: 8093
#  ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
spring:
  application:
    name: outbox-engine

outbox:
  engine:
    delay: 60 * 1000 * 60



