server:
  port: 8093
#  ${PORT:0}

spring:
  application:
    name: outbox-engine

##################### KAFKA ############################
  kafka:
    topics:
      new-log-added: new-log-added
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.meysam.logcollector.outboxengine.config.KafkaSerializerConfig
      #      buffer default size is 32 MB
      #      buffer:
      #        memory: 1048576
      retries: 0
  #  ############## DATA SOURCE ####################
  #  h2:
  #    console:
  #      enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    #    url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true



outbox:
  engine:
    delay: 60 * 1000 * 60
  retry:
    count: 3
  processing:
    page:
      size: 100
