server:
  port: 8012

spring:
  application:
    name: config-server
  rabbitmq:
#    host: host.minikube.internal
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      bus:
        enabled: true
      import-check:
        enabled: false
      server:
        native:
          search-locations: classpath:/config
#          /home/meysam/Meysam_Workspace/github/repositories/MyConfigServer-main/config/dev, /home/meysam/Meysam_Workspace/github/repositories/MyConfigServer-main/config/test
#        bootstrap: true
